# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clue',
                'doc_host': 'https://ArthurConner.github.io',
                'git_url': 'https://github.com/ArthurConner/clue',
                'lib_path': 'clue'},
  'syms': { 'clue.core': { 'clue.core.cIndentity': ('core.html#cindentity', 'clue/core.py'),
                           'clue.core.cardFull': ('core.html#cardfull', 'clue/core.py'),
                           'clue.core.cardShort': ('core.html#cardshort', 'clue/core.py'),
                           'clue.core.chooseCard': ('core.html#choosecard', 'clue/core.py'),
                           'clue.core.printHand': ('core.html#printhand', 'clue/core.py')}}}
