# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clue',
                'doc_host': 'https://ArthurConner.github.io',
                'git_url': 'https://github.com/ArthurConner/clue',
                'lib_path': 'clue'},
  'syms': {'clue.core': {'clue.core.foo': ('core.html#foo', 'clue/core.py')}}}
