# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['people', 'weapons', 'rooms', 'cardFull', 'cardShort', 'cIndentity', 'printHand', 'chooseCard']

# %% ../nbs/00_core.ipynb 3
from termcolor import colored
from random import shuffle
import emoji

# %% ../nbs/00_core.ipynb 4
def cardFull(info):
    name,color, icon = info[:3]
    if len(icon) > 0:
        ret = icon + " " + colored(name,color)
    else:
        ret = colored(name,color)
    
    return ret

def cardShort(info):
    if len(info) < 3:
        return cardFull(info)
    color,icon, name = info[1:]
    if len(icon) > 0:
        ret = icon + " " + colored(name,color)
    else:
        ret = colored(name,color)
   
    return  ret


# %% ../nbs/00_core.ipynb 8
people = []
people.append(["Miss Scarlet","red",u"\U0001f460","Scar."])
people.append(["Colonel Mustard","yellow",u"\U0001F9D0","Must."])
people.append([" Mrs. White","white",u"\u2661"," White"])
people.append(["Mr. Green","green",u"\U0001F409","Green"])
people.append(["Professor Plum","magenta",u"\U0001F346","Plum "])
people.append(["Mrs. Peacock","blue",u"\U0001F99A","Peac."])


# %% ../nbs/00_core.ipynb 9
weapons = []
weapons.append(["Knife","blue",u"\U0001F52A","Knife"])
weapons.append(["Revolver","blue",u"\U0001F52B","Gun"])
weapons.append(["Rope","blue",emoji.emojize(":knot:"),"Rope"])
weapons.append(["Wrench","blue",emoji.emojize(":wrench:"),"Wrench"])
weapons.append(["Candlestick","blue",emoji.emojize(":candle:"),"Candle"])
weapons.append(["Lead Pipe","blue",emoji.emojize(":plunger:"),"Pipe"])

# %% ../nbs/00_core.ipynb 10
rooms = []
rooms.append(["Ball Room","yellow","","Ball"])
rooms.append(["Billiard Room","yellow","","Bill"])
rooms.append(["Conservatory","yellow","","Consv"])
rooms.append(["Dining Room","yellow","","Dining"])
rooms.append(["Hall","yellow","","Hall"])
rooms.append(["Kitchen","yellow","","Kitch"])
rooms.append(["Lounge","yellow","","Lounge"])
rooms.append(["Kitchen","yellow","","Lib"])
rooms.append(["Study","yellow","","Study"])

# %% ../nbs/00_core.ipynb 11
def cIndentity(x):
  return x[0]
    
def printHand(hand,view=cIndentity):
    container = []
    line = [view(card) for card in hand]
    print(' '.join(line))


# %% ../nbs/00_core.ipynb 16
def chooseCard(hand,view=cIndentity,fmt="fancy_grid"):
    container = []
    i = 1
    choices = []
    ml = max([len(x[0]) for x in hand])
    choice = -1
    for card in hand:
        face = view(card)
        #face.append(i)
        color = card[1]
        container.append(colored(str(i) +")",color) + face)
        i += 1
    while choice < 1:
        for card in container:
            print(card)
        choice = int(input("Choose from 1 to " +  str(len(choices))+": "))
       
        if (choice > 0) and (choice <= len(choices)):
            return choice
        print(str(choice) + " is not in range")
        choice = -1
            


